package Telas;

import javax.swing.JPanel;

import Telas.investimentotela;

public class Taxas {
    
      // Variables declaration - do not modify                     
    private javax.swing.JButton buttonContinue3;
    private javax.swing.JButton buttonCustoms;
    private javax.swing.JButton buttonJustice;
    private javax.swing.JButton buttonMiscellaneous;
    private javax.swing.JButton buttonSales;
    private javax.swing.JPanel choiceTaxJPanel;
    private javax.swing.JLabel choiceTaxLabel;
    private javax.swing.JLabel customsLabel;
    private javax.swing.JPanel economyJPanel3;
    private javax.swing.JLabel economyPlayerLabel3;
    private javax.swing.JLabel iconCoinLabel3;
    private javax.swing.JLabel iconLandsLabel3;
    private javax.swing.JLabel iconPlayerLabel3;
    private javax.swing.JLabel iconTreasureLabel;
    private javax.swing.JLabel imageLabel3;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel justiceLabel;
    private javax.swing.JPanel landsJPanel3;
    private javax.swing.JLabel landsLabel3;
    private javax.swing.JLabel landsPlayerLabel3;
    private javax.swing.JLabel miscellaneousLabel;
    private javax.swing.JLabel namePlayerLabel3;
    private javax.swing.JPanel namePlayerPanel3;
    private javax.swing.JLabel salesLabel;
    private javax.swing.JPanel taxCustomsJPanel;
    private javax.swing.JLabel taxCustomsLabel;
    private javax.swing.JPanel taxJusticeJPanel;
    private javax.swing.JLabel taxJusticeLabel;
    private javax.swing.JPanel taxMiscellaneousJPanel;
    private javax.swing.JLabel taxMiscellaneousLabel;
    private javax.swing.JPanel taxSalesJPanel;
    private javax.swing.JLabel taxSalesLabel;
    private javax.swing.JPanel treasureJPanel;
    private javax.swing.JLabel treasureLabel;
    private javax.swing.JLabel treasurePlayerLabel;
    private javax.swing.JPanel Jpanel1;
    private javax.swing.JPanel bufferTaxa;

    investimentotela investimento = new investimentotela();

    public Taxas(){
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        taxCustomsJPanel = new javax.swing.JPanel();
        taxCustomsLabel = new javax.swing.JLabel();
        customsLabel = new javax.swing.JLabel();
        taxSalesJPanel = new javax.swing.JPanel();
        taxSalesLabel = new javax.swing.JLabel();
        salesLabel = new javax.swing.JLabel();
        taxMiscellaneousJPanel = new javax.swing.JPanel();
        taxMiscellaneousLabel = new javax.swing.JLabel();
        miscellaneousLabel = new javax.swing.JLabel();
        taxJusticeJPanel = new javax.swing.JPanel();
        taxJusticeLabel = new javax.swing.JLabel();
        justiceLabel = new javax.swing.JLabel();
        buttonMiscellaneous = new javax.swing.JButton();
        buttonCustoms = new javax.swing.JButton();
        buttonSales = new javax.swing.JButton();
        buttonJustice = new javax.swing.JButton();
        buttonContinue3 = new javax.swing.JButton();
        treasureJPanel = new javax.swing.JPanel();
        treasureLabel = new javax.swing.JLabel();
        iconTreasureLabel = new javax.swing.JLabel();
        treasurePlayerLabel = new javax.swing.JLabel();
        choiceTaxJPanel = new javax.swing.JPanel();
        choiceTaxLabel = new javax.swing.JLabel();
        namePlayerPanel3 = new javax.swing.JPanel();
        namePlayerLabel3 = new javax.swing.JLabel();
        iconPlayerLabel3 = new javax.swing.JLabel();
        economyJPanel3 = new javax.swing.JPanel();
        iconCoinLabel3 = new javax.swing.JLabel();
        economyPlayerLabel3 = new javax.swing.JLabel();
        landsJPanel3 = new javax.swing.JPanel();
        landsPlayerLabel3 = new javax.swing.JLabel();
        iconLandsLabel3 = new javax.swing.JLabel();
        landsLabel3 = new javax.swing.JLabel();
        imageLabel3 = new javax.swing.JLabel();
        Jpanel1 = new javax.swing.JPanel();
        bufferTaxa = new javax.swing.JPanel();

        Jpanel1.setBackground(new java.awt.Color(196, 199, 197));
        Jpanel1.setFont(new java.awt.Font("Verdana", 0, 25)); // NOI18N
        Jpanel1.setPreferredSize(new java.awt.Dimension(1280, 768));
        Jpanel1.setLayout(null);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        Jpanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 90, 1274, 10);

        taxCustomsJPanel.setBackground(new java.awt.Color(102, 102, 102));
        taxCustomsJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taxCustomsLabel.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        taxCustomsLabel.setText("Taxas Alfandegárias");

        customsLabel.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        customsLabel.setForeground(new java.awt.Color(255, 255, 255));
        customsLabel.setText("85%");

        javax.swing.GroupLayout taxCustomsJPanelLayout = new javax.swing.GroupLayout(taxCustomsJPanel);
        taxCustomsJPanel.setLayout(taxCustomsJPanelLayout);
        taxCustomsJPanelLayout.setHorizontalGroup(
            taxCustomsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxCustomsJPanelLayout.createSequentialGroup()
                .addGroup(taxCustomsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxCustomsJPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(taxCustomsLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(taxCustomsJPanelLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(customsLabel)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        taxCustomsJPanelLayout.setVerticalGroup(
            taxCustomsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxCustomsJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taxCustomsLabel)
                .addGap(18, 18, 18)
                .addComponent(customsLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Jpanel1.add(taxCustomsJPanel);
        taxCustomsJPanel.setBounds(20, 250, 300, 110);

        taxSalesJPanel.setBackground(new java.awt.Color(102, 102, 102));
        taxSalesJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taxSalesLabel.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        taxSalesLabel.setText("Taxas de Vendas");

        salesLabel.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        salesLabel.setForeground(new java.awt.Color(255, 255, 255));
        salesLabel.setText("50%");

        javax.swing.GroupLayout taxSalesJPanelLayout = new javax.swing.GroupLayout(taxSalesJPanel);
        taxSalesJPanel.setLayout(taxSalesJPanelLayout);
        taxSalesJPanelLayout.setHorizontalGroup(
            taxSalesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxSalesJPanelLayout.createSequentialGroup()
                .addGroup(taxSalesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(taxSalesJPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(taxSalesLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(taxSalesJPanelLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(salesLabel)))
                .addGap(35, 35, 35))
        );
        taxSalesJPanelLayout.setVerticalGroup(
            taxSalesJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxSalesJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taxSalesLabel)
                .addGap(18, 18, 18)
                .addComponent(salesLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Jpanel1.add(taxSalesJPanel);
        taxSalesJPanel.setBounds(340, 250, 294, 110);

        taxMiscellaneousJPanel.setBackground(new java.awt.Color(102, 102, 102));
        taxMiscellaneousJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taxMiscellaneousLabel.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        taxMiscellaneousLabel.setText("Taxas Diversas");

        miscellaneousLabel.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        miscellaneousLabel.setForeground(new java.awt.Color(255, 255, 255));
        miscellaneousLabel.setText("25%");

        javax.swing.GroupLayout taxMiscellaneousJPanelLayout = new javax.swing.GroupLayout(taxMiscellaneousJPanel);
        taxMiscellaneousJPanel.setLayout(taxMiscellaneousJPanelLayout);
        taxMiscellaneousJPanelLayout.setHorizontalGroup(
            taxMiscellaneousJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taxMiscellaneousJPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(taxMiscellaneousLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(taxMiscellaneousJPanelLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(miscellaneousLabel)
                .addContainerGap())
        );
        taxMiscellaneousJPanelLayout.setVerticalGroup(
            taxMiscellaneousJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxMiscellaneousJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taxMiscellaneousLabel)
                .addGap(18, 18, 18)
                .addComponent(miscellaneousLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Jpanel1.add(taxMiscellaneousJPanel);
        taxMiscellaneousJPanel.setBounds(650, 250, 289, 110);

        taxJusticeJPanel.setBackground(new java.awt.Color(102, 102, 102));
        taxJusticeJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        taxJusticeLabel.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        taxJusticeLabel.setText("Justiça");

        justiceLabel.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        justiceLabel.setForeground(new java.awt.Color(255, 255, 255));
        justiceLabel.setText("Moderada");

        javax.swing.GroupLayout taxJusticeJPanelLayout = new javax.swing.GroupLayout(taxJusticeJPanel);
        taxJusticeJPanel.setLayout(taxJusticeJPanelLayout);
        taxJusticeJPanelLayout.setHorizontalGroup(
            taxJusticeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxJusticeJPanelLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(taxJusticeLabel)
                .addGap(107, 107, 107))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, taxJusticeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(justiceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
        );
        taxJusticeJPanelLayout.setVerticalGroup(
            taxJusticeJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taxJusticeJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taxJusticeLabel)
                .addGap(18, 18, 18)
                .addComponent(justiceLabel)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        Jpanel1.add(taxJusticeJPanel);
        taxJusticeJPanel.setBounds(960, 250, 297, 110);

        buttonMiscellaneous.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        buttonMiscellaneous.setText("Taxas Diversas");
        buttonMiscellaneous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMiscellaneousActionPerformed(evt);
            }
        });
        Jpanel1.add(buttonMiscellaneous);
        buttonMiscellaneous.setBounds(700, 520, 417, 39);

        buttonCustoms.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        buttonCustoms.setText("Taxas Alfandegárias");
        buttonCustoms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCustomsActionPerformed(evt);
            }
        });
        Jpanel1.add(buttonCustoms);
        buttonCustoms.setBounds(150, 520, 417, 39);

        buttonSales.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        buttonSales.setText("Taxas de Vendas");
        buttonSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalesActionPerformed(evt);
            }
        });
        Jpanel1.add(buttonSales);
        buttonSales.setBounds(150, 600, 417, 39);

        buttonJustice.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        buttonJustice.setText("Justiça");
        buttonJustice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonJusticeActionPerformed(evt);
            }
        });
        Jpanel1.add(buttonJustice);
        buttonJustice.setBounds(700, 600, 417, 39);

        buttonContinue3.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        buttonContinue3.setText("Continue");
        buttonContinue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinue3ActionPerformed(evt);
            }
        });
        Jpanel1.add(buttonContinue3);
        buttonContinue3.setBounds(540, 660, 186, 39);

        treasureJPanel.setBackground(new java.awt.Color(102, 102, 102));
        treasureJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        treasureLabel.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        treasureLabel.setText("Tesouro Nacional:");

        treasurePlayerLabel.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        treasurePlayerLabel.setForeground(new java.awt.Color(255, 255, 255));
        treasurePlayerLabel.setText("$ 5.000");

        javax.swing.GroupLayout treasureJPanelLayout = new javax.swing.GroupLayout(treasureJPanel);
        treasureJPanel.setLayout(treasureJPanelLayout);
        treasureJPanelLayout.setHorizontalGroup(
            treasureJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, treasureJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconTreasureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(treasureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(treasurePlayerLabel)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        treasureJPanelLayout.setVerticalGroup(
            treasureJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treasureJPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(treasureJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconTreasureLabel)
                    .addGroup(treasureJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(treasureLabel)
                        .addComponent(treasurePlayerLabel)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Jpanel1.add(treasureJPanel);
        treasureJPanel.setBounds(20, 130, 450, 80);

        choiceTaxJPanel.setBackground(new java.awt.Color(102, 102, 102));
        choiceTaxJPanel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        choiceTaxLabel.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        choiceTaxLabel.setText("Alterar as Taxas:");

        javax.swing.GroupLayout choiceTaxJPanelLayout = new javax.swing.GroupLayout(choiceTaxJPanel);
        choiceTaxJPanel.setLayout(choiceTaxJPanelLayout);
        choiceTaxJPanelLayout.setHorizontalGroup(
            choiceTaxJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(choiceTaxJPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(choiceTaxLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        choiceTaxJPanelLayout.setVerticalGroup(
            choiceTaxJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, choiceTaxJPanelLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(choiceTaxLabel)
                .addGap(23, 23, 23))
        );

        Jpanel1.add(choiceTaxJPanel);
        choiceTaxJPanel.setBounds(20, 410, 256, 80);

        namePlayerPanel3.setBackground(new java.awt.Color(102, 102, 102));
        namePlayerPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        namePlayerLabel3.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        namePlayerLabel3.setText("Princesa Mari do Reino do Norte");

        iconPlayerLabel3.setIcon(new javax.swing.ImageIcon("src/resources/icons/coroa-holandesa.png")); // NOI18N

        javax.swing.GroupLayout namePlayerPanel3Layout = new javax.swing.GroupLayout(namePlayerPanel3);
        namePlayerPanel3.setLayout(namePlayerPanel3Layout);
        namePlayerPanel3Layout.setHorizontalGroup(
            namePlayerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, namePlayerPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconPlayerLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namePlayerLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        namePlayerPanel3Layout.setVerticalGroup(
            namePlayerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(namePlayerPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(namePlayerPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconPlayerLabel3)
                    .addComponent(namePlayerLabel3))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        Jpanel1.add(namePlayerPanel3);
        namePlayerPanel3.setBounds(10, 10, 457, 70);

        economyJPanel3.setBackground(new java.awt.Color(102, 102, 102));
        economyJPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        iconCoinLabel3.setIcon(new javax.swing.ImageIcon("src/resources/icons/moedas_3.png")); // NOI18N

        economyPlayerLabel3.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        economyPlayerLabel3.setForeground(new java.awt.Color(255, 255, 255));
        economyPlayerLabel3.setText("$ 2.000");

        javax.swing.GroupLayout economyJPanel3Layout = new javax.swing.GroupLayout(economyJPanel3);
        economyJPanel3.setLayout(economyJPanel3Layout);
        economyJPanel3Layout.setHorizontalGroup(
            economyJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(economyJPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(iconCoinLabel3)
                .addGap(18, 18, 18)
                .addComponent(economyPlayerLabel3)
                .addContainerGap(66, Short.MAX_VALUE))
        );
        economyJPanel3Layout.setVerticalGroup(
            economyJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(economyJPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(economyJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconCoinLabel3)
                    .addComponent(economyPlayerLabel3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Jpanel1.add(economyJPanel3);
        economyJPanel3.setBounds(490, 10, 270, 70);

        landsJPanel3.setBackground(new java.awt.Color(102, 102, 102));
        landsJPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        landsPlayerLabel3.setFont(new java.awt.Font("Verdana", 1, 22)); // NOI18N
        landsPlayerLabel3.setText("Área do Reino:");

        iconLandsLabel3.setIcon(new javax.swing.ImageIcon("src/resources/icons/fazenda.png")); // NOI18N

        landsLabel3.setFont(new java.awt.Font("Verdana", 1, 25)); // NOI18N
        landsLabel3.setForeground(new java.awt.Color(255, 255, 255));
        landsLabel3.setText("2.000 Hectares");

        javax.swing.GroupLayout landsJPanel3Layout = new javax.swing.GroupLayout(landsJPanel3);
        landsJPanel3.setLayout(landsJPanel3Layout);
        landsJPanel3Layout.setHorizontalGroup(
            landsJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landsJPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(iconLandsLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(landsPlayerLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(landsLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        landsJPanel3Layout.setVerticalGroup(
            landsJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(landsJPanel3Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(landsJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLandsLabel3)
                    .addGroup(landsJPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(landsPlayerLabel3)
                        .addComponent(landsLabel3)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Jpanel1.add(landsJPanel3);
        landsJPanel3.setBounds(790, 10, 470, 70);

        imageLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/images/medieval-pixel-art.jpg"))); // NOI18N
        Jpanel1.add(imageLabel3);
        imageLabel3.setBounds(0, 0, 1280, 770);

        bufferTaxa.add(Jpanel1);
    }// </editor-fold>        

    private void buttonMiscellaneousActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void buttonCustomsActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void buttonSalesActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void buttonJusticeActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void buttonContinue3ActionPerformed(java.awt.event.ActionEvent evt) {                                                
        bufferTaxa.remove(Jpanel1);
        bufferTaxa.add(investimento.getPanel());
        bufferTaxa.revalidate();
        bufferTaxa.repaint();
    }        
    
    public JPanel getPanel(){
        return bufferTaxa;
    }
}
